services:
  sublime_postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: sublime_postgres
    environment:
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      PGDATA: /data/postgres
    env_file: sublime.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - net
  sublime_dashboard:
    image: sublimesec/dashboard:dev
    restart: unless-stopped
    container_name: sublime_dashboard
    ports:
      - "0.0.0.0:3000:80"
    networks:
      - net
    env_file: sublime.env
    environment:
      MANTIS_HOST_URL: "http://host.docker.internal:8000"
  sublime_redis:
    image: redis:6.2
    restart: unless-stopped
    container_name: sublime_redis
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - net
  sublime_nipper:
    image: 948971135452.dkr.ecr.us-east-1.amazonaws.com/nipper-python-dev:dev
    restart: unless-stopped
    container_name: sublime_nipper
    env_file: sublime.env
    ports:
      - "8300:8000"
    networks:
      - net
    environment:
      NIPPER_BUCKET: "nipper-artifacts"
      BUCKET_ENDPOINT_URL: "http://sublimes3:8110"
      DD_TRACE_ENABLED: false
    depends_on:
      - sublime_create_buckets
  sublime_strelka_frontend:
    image: sublimesec/strelka-frontend:0.3
    restart: unless-stopped
    command: strelka-frontend
    ports:
      - "57314:57314"
    networks:
      - net
    volumes:
      - ./configs/frontend/:/etc/strelka/:ro
      - logs:/var/log/strelka/
    depends_on:
      - sublime_strelka_coordinator
    deploy:
      replicas: 1
  sublime_strelka_backend:
    image: sublimesec/strelka-backend:0.3
    restart: unless-stopped
    command: strelka-backend
    shm_size: 512mb
    networks:
      - net
    volumes:
      - ./configs/backend/:/etc/strelka/:ro
    depends_on:
      - sublime_strelka_coordinator
    deploy:
      replicas: 2
  sublime_strelka_manager:
    image: sublimesec/strelka-manager:0.3
    restart: unless-stopped
    command: strelka-manager
    container_name: sublime_strelka_manager_1
    networks:
      - net
    volumes:
      - ./configs/manager/:/etc/strelka/:ro
    depends_on:
      - sublime_strelka_coordinator
  sublime_strelka_coordinator:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    container_name: sublime_strelka_coordinator_1
    networks:
      - net
  sublime_screenshot_service:
    image: sublimesec/render-email-html:0.1
    restart: unless-stopped
    ports:
      - "8100:8100"
    environment:
      - S3_ENDPOINT=http://sublimes3:8110
      - SCREENSHOT_BUCKET=email-screenshots
      - AWS_REGION=us-east-1
      - DISABLE_DD=true
    container_name: sublime_screenshot_service
    env_file: sublime.env
    networks:
      - net
    depends_on:
      - sublime_create_buckets
  sublime_azurite:
      container_name: sublime_azurite
      image: mcr.microsoft.com/azure-storage/azurite
      restart: unless-stopped
      networks:
        - net
      ports:
        - "10000:10000"  # Blob service
        - "10001:10001"  # Queue service
        - "10002:10002"  # Table service
      volumes:
        - azurite_data:/data
      command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --skipApiVersionCheck
  sublime_create_azure_blob_containers:
    image: mcr.microsoft.com/azure-cli
    depends_on:
      - sublime_azurite
    networks:
      - net
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://sublime_azurite:10000/devstoreaccount1;"
    command: >
      bash -c "
      az storage container create --name email-screenshots &&
      az storage container create --name events &&
      az storage container create --name message-storage &&
      az storage container create --name message-export &&
      az storage container create --name nipper-artifacts
      "
  # Keep this name as sublimes3 because underscores don't play nice with certain endpoint validation
  sublimes3:
    container_name: sublimes3
    image: minio/minio
    restart: unless-stopped
    networks:
      - net
    ports:
      - "8110:8110"
    volumes:
      - s3_data:/data
    env_file: sublime.env
    entrypoint: >
      /bin/sh -c "
      export MINIO_ROOT_USER=$$AWS_ACCESS_KEY_ID;
      export MINIO_ROOT_PASSWORD=$$AWS_SECRET_ACCESS_KEY;
      minio server --address 0.0.0.0:8110 --console-address 0.0.0.0:8111  /data;
      "
  sublime_create_buckets:
    image: minio/mc
    depends_on:
      - sublimes3
    networks:
      - net
    env_file: sublime.env
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio http://sublimes3:8110 $$AWS_ACCESS_KEY_ID $$AWS_SECRET_ACCESS_KEY;
      /usr/bin/mc mb myminio/email-screenshots;
      /usr/bin/mc mb myminio/events;
      /usr/bin/mc mb myminio/message-storage;
      /usr/bin/mc mb myminio/message-export;
      /usr/bin/mc mb myminio/nipper-artifacts;
      /usr/bin/mc ls myminio;
      exit 0;
      "
  sublime_hydra:
    image: sublimesec/hydra-cpu:dev
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      - net
    container_name: sublime_hydra
    environment:
      WORKERS: 2
      WEB_CONCURRENCY: 5
      KEEP_ALIVE: 2
  sublime_localstack:
    container_name: sublime_localstack
    image: localstack/localstack:4.10.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    networks:
      - net
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=0
    volumes:
      - localstack:/var/lib/localstack

networks:
  net:
    driver: bridge
volumes:
  postgres:
  logs:
  s3_data:
  localstack:
  azurite_data:
