version: '3'

services:
  mantis:
    image: sublimesec/mantis:dev
    container_name: mantis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      REDIS_HOST: redis
    env_file: sublime.dev.env
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - net
    depends_on:
      - postgres
  bora_lite:
    image: sublimesec/bora-lite:dev
    container_name: bora-lite
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      REDIS_HOST: redis
    env_file: sublime.dev.env
    networks:
      - net
    depends_on:
      - mantis
      - redis
  postgres:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      PGDATA: /data/postgres
    env_file: sublime.dev.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - net
    restart: unless-stopped
  dashboard:
    image: sublimesec/dashboard:dev
    container_name: dashboard
    ports:
      - "0.0.0.0:3000:80"
    networks:
      - net
    env_file: sublime.dev.env
    depends_on:
      - mantis
  redis:
    image: redis:6.2
    container_name: redis
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
