version: '3'

services:
  mantis:
    image: sublimesec/mantis:latest
    container_name: mantis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    env_file: sublime.env
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - net
    depends_on:
      - postgres
  bora_lite:
    image: sublimesec/bora-lite:latest
    container_name: bora-lite
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    env_file: sublime.env
    networks:
      - net
    depends_on:
      - mantis
      - rabbitmq
      - redis
  postgres:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_USER: sublime
      POSTGRES_DB: mantis
      PGDATA: /data/postgres
    env_file: sublime.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - net
    restart: unless-stopped
  dashboard:
    image: sublimesec/dashboard:latest
    container_name: dashboard
    ports:
      - "0.0.0.0:3000:80"
    networks:
      - net
    env_file: sublime.env
    depends_on:
      - mantis
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    tty: true
    ports:
      - "15671:15671"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error}]
    env_file: sublime.env
    networks:
      - net
    restart: unless-stopped
  redis:
    image: redis:6.2
    container_name: redis
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
