version: 1
formatters:
  simple:
    format: '%(asctime)s - [%(levelname)s] %(name)s [%(module)s.%(funcName)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
loggers:
  OpenSSL:
    propagate: 0
  bs4:
    propagate: 0
  bz2:
    propagate: 0
  chardet:
    propagate: 0
  docx:
    propagate: 0
  elftools:
    propagate: 0
  email:
    propagate: 0
  entropy:
    propagate: 0
  esprima:
    propagate: 0
  gzip:
    propagate: 0
  hashlib:
    propagate: 0
  json:
    propagate: 0
  libarchive:
    propagate: 0
  lxml:
    propagate: 0
  lzma:
    propagate: 0
  macholibre:
    propagate: 0
  olefile:
    propagate: 0
  oletools:
    propagate: 0
  pymupdf:
    propagate: 0
  pefile:
    propagate: 0
  pgpdump:
    propagate: 0
  pygments:
    propagate: 0
  pylzma:
    propagate: 0
  rarfile:
    propagate: 0
  requests:
    propagate: 0
  rpmfile:
    propagate: 0
  ssdeep:
    propagate: 0
  tarfile:
    propagate: 0
  tnefparse:
    propagate: 0
  yara:
    propagate: 0
  zipfile:
    propagate: 0
  zlib:
    propagate: 0
