name: Platform PR CI

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: Validate Platform Installation
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: github.ref != 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::948971135452:role/ci-sublime-platform-ecr-read
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: github.ref != 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "948971135452"

      - name: Make ECR credentials available to sudo
        if: github.ref != 'refs/heads/main'
        run: sudo cp -r $HOME/.docker /root/

      - name: Install Platform
        run: |
          interactive=false clone_platform=false ./install-and-launch.sh

      - name: Check Health
        run: |
          ./postflight_checks.sh
